from imageio import imread, imwrite
import matplotlib.pyplot as plt
import numpy
from sys import getsizeof

class imgCutter:
    """ """
    def __init__(self, path):
        self.img = imread(path)

    def cut_image(self, width=200, height=200):
        self.rows = self.img.shape[0] // height + 1
        self.cols = self.img.shape[1] // width + 1
        self.parts = [[0 for i in range(self.cols)] for j in range(self.rows)]
        for i in range(self.rows):
            for j in range(self.cols):
                # All arrays generated by basic slicing are always views of the original array.
                self.parts[i][j] = self.img[i * height:(i+1)*height, j*width:(j+1)*width, :]
        print(getsizeof(self.img))
        print(getsizeof(self.parts))

    def show_image(self):
        plt.imshow(self.img)
        plt.show()

    def show_parts(self):
        fig = plt.figure(figsize=(self.rows, self.cols))
        for i in range(self.rows):
            for j in range(self.cols):
                num = i * self.cols + j + 1
                img = self.parts[i][j]
                fig.add_subplot(self.rows, self.cols, num)
                plt.imshow(img)
        plt.show()
    
    def save_parts(self, dir):
        pass
    



im = imgCutter('/home/lodya/Documents/DigDes/sat-img-lab/MOS_SK_GK4_250/MOS_SK_GK4_250.tif')
im.cut_image()
im.show_parts()
